use std::error::Error;
use super::metadata::DeviceMetadata;

pub trait Controller: Send {
    fn poll_events(&mut self) -> Result<Vec<ControllerEvent>, Box<dyn Error>>;
    fn get_metadata(&self) -> DeviceMetadata;
}

/// Events generated by controllers
#[derive(Debug, Clone, PartialEq)]
pub enum ControllerEvent {
    ButtonPress {
        button: Button,
        pressed: bool,
    },
    AxisMove {
        axis: Axis,
        value: f32,
    },
    #[cfg(target_os = "linux")]
    TouchpadMove {
        x: Option<i32>,
        y: Option<i32>,
    },
}

/// Supported controller axes
#[derive(Debug, Clone, PartialEq)]
pub enum Axis {
    LeftStickX,
    LeftStickY,
    RightStickX,
    RightStickY,
    L2,
    R2,
    #[cfg(target_os = "linux")]
    TrackpadX,
    #[cfg(target_os = "linux")]
    TrackpadY,
    Unknown,
}

/// Supported controller buttons
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Button {
    Cross,
    Circle,
    Square,
    Triangle,
    L1,
    R1,
    L2,
    R2,
    Share,
    Options,
    PS,
    L3,
    R3,
    DpadUp,
    DpadDown,
    DpadLeft,
    DpadRight,
    Unknown,
}