[package]
name = "ps4_midi_mapper"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-xinput = "1.3.0"
hidapi = "2.0.0"
windows = { version = "0.54.0", features = ["Win32_UI_Input"] }

# Para soporte de Linux
[target.'cfg(target_os = "linux")'.dependencies]
gilrs = { version = "0.9", features = ["serde"] }
evdev = "0.12"
