[package]
name = "ps4_midi_mapper"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.48"
default-features = true
features = [
    "Win32_Foundation",
    "Win32_System_SystemServices",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_HumanInterfaceDevice",
    "Win32_System_Com",
    "Win32_System_LibraryLoader"
]
[dependencies]
rusty-xinput = "1.3.0"
hidapi = "2.0.0"
midir = "0.10.1"
log = "0.4.20"

# Linux support
[target.'cfg(target_os = "linux")'.dependencies]
gilrs = { version = "0.9", features = ["serde"] }
evdev = "0.12"

[build-dependencies]
winres = "0.1"

[dev-dependencies]
serial_test = "0.6.0"  # Optional: For serial test execution